version: '3'
services:
  web:
    container_name: nginx1
    ports:
      - "8080:80"
    volumes:
            - "/home/eduardo-fernandez/docker-images/docker-compose/html:/usr/share/nginx/html"
    image: nginx
