* LABEL se utiliza agregar metadata a la imagen.
  LABEL version=1.0
  LABEL description="This is an apache image"
  LABEL vendor=yo
* USER se utiliza para establecer el usuario que debe ejecutar una tarea en particular.
  RUN useradd eduardo
  USER eduardo
  RUN echo "$(whoami)" > /tmp/user2.html
  USER root
  RUN cp /tmp/user2.html /var/www/html
* Para visualizar los logs del contenedor: docker logs <nombre del contenedor>.
* VOLUME se utiliza para persistir la data del contenedor después de que finalice su ejecución.
