version: '3'
services:
  web:
    container_name: apache
    ports:
      - "8080:80"
    image: httpd
    networks:
      - net-test
  web1:
    container_name: apache1
    ports:
      - "8081:80"
    image: httpd
    networks:
      - net-test
networks:
  net-test:
